src/Entity/Member.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MemberRepository")
 * @UniqueEntity(fields="email", message="L'adresse email est déjà utilisée")
 * @UniqueEntity(fields="username", message="Le nom de compte est déjà utilisé")
 */
class Member implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $validationtoken;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $passwordtoken;

    /**
     * @ORM\OneToMany(targetEntity="Trick", mappedBy="authorid")
     */
    private $figures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="authorid")
     */
    private $comments;

    /**
     * @ORM\Column(type="array")
     */
    private $Rank;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     * @Assert\File(mimeTypes={ "image/jpeg","image/png","image/gif" })
     */
    private $Avatar;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    private $saveAvatar;

    public function __construct()
    {
        $this->figures = new ArrayCollection();
        $this->comments = new ArrayCollection();

        $this->Rank = array('ROLE_USER');
        $this->saveAvatar = $this->getAvatar();
        $this->active = false;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getValidationtoken(): ?string
    {
        return $this->validationtoken;
    }

    public function setValidationtoken(string $validationtoken): self
    {
        $this->validationtoken = $validationtoken;

        return $this;
    }

    public function getPasswordtoken(): ?string
    {
        return $this->passwordtoken;
    }

    public function setPasswordtoken(string $passwordtoken): self
    {
        $this->passwordtoken = $passwordtoken;

        return $this;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getFigures(): Collection
    {
        return $this->figures;
    }

    public function addFigure(Trick $figure): self
    {
        if (!$this->figures->contains($figure)) {
            $this->figures[] = $figure;
            $figure->setAuthorid($this);
        }

        return $this;
    }

    public function removeFigure(Trick $figure): self
    {
        if ($this->figures->contains($figure)) {
            $this->figures->removeElement($figure);
            // set the owning side to null (unless already changed)
            if ($figure->getAuthorid() === $this) {
                $figure->setAuthorid(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthorid($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthorid() === $this) {
                $comment->setAuthorid(null);
            }
        }

        return $this;
    }

    public function getRank()
    {
        return $this->Rank;
    }

    public function setRank(array $Rank): self
    {
        $this->Rank = $Rank;

        return $this;
    }

    public function getSalt()
    {
        // The bcrypt and argon2i algorithms don't require a separate salt.
        // You *may* need a real salt if you choose a different encoder.
        return null;
    }

    public function eraseCredentials()
    {
    }

    public function getRoles()
    {
        return $this->Rank;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->active,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->active,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized, array('allowed_classes' => false));
    }

    public function getAvatar()
    {
        return $this->Avatar;
    }

    public function setAvatar($Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    public function getSaveAvatar()
    {
        return $this->saveAvatar;
    }

    public function setSaveAvatar($Avatar): self
    {
        $this->saveAvatar = $Avatar;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->active;
    }
}

src/Entity/Trick.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 * @UniqueEntity(fields="name", message="La figure existe déjà sur le site internet")
 */
class Trick
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="TrickGroup")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="groupid_id", referencedColumnName="id")
     * })
     */
    private $groupid;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Member", inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $authorid;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trickid")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="TrickMedia", mappedBy="IdTrick")
     */
    private $trickMedia;

    /**
     * @ORM\Column(type="datetime")
     */
    private $PublishedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdatedDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TrickMedia", inversedBy="tricks")
     * @ORM\JoinColumn(nullable=true)
     */
    private $CoverMedia;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->trickMedia = new ArrayCollection();
        $this->active = false;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getGroupid(): ?TrickGroup
    {
        return $this->groupid;
    }

    public function setGroupid(?TrickGroup $groupid): self
    {
        $this->groupid = $groupid;

        return $this;
    }

    public function getAuthorid(): ?Member
    {
        return $this->authorid;
    }

    public function setAuthorid(?Member $authorid): self
    {
        $this->authorid = $authorid;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrickid($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrickid() === $this) {
                $comment->setTrickid(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TrickMedia[]
     */
    public function getTrickMedia(): Collection
    {
        return $this->trickMedia;
    }

    public function addTrickMedia(TrickMedia $trickMedia): self
    {
        if (!$this->trickMedia->contains($trickMedia)) {
            $this->trickMedia[] = $trickMedia;
            $trickMedia->setIdFigure($this);
        }

        return $this;
    }

    public function removeTrickMedia(TrickMedia $trickMedia): self
    {
        if ($this->trickMedia->contains($trickMedia)) {
            $this->trickMedia->removeElement($trickMedia);
            // set the owning side to null (unless already changed)
            if ($trickMedia->getIdFigure() === $this) {
                $trickMedia->setIdFigure(null);
            }
        }

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;

        return $this;
    }

    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->UpdatedDate;
    }

    public function setUpdatedDate(\DateTimeInterface $UpdatedDate): self
    {
        $this->UpdatedDate = $UpdatedDate;

        return $this;
    }

    public function getCoverMedia(): ?TrickMedia
    {
        return $this->CoverMedia;
    }

    public function setCoverMedia(?TrickMedia $CoverMedia): self
    {
        $this->CoverMedia = $CoverMedia;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

src/Entity/TrickPicture.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickPictureRepository")
 */
class TrickPicture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Trick", inversedBy="figurePictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $IdFigure;

    /**
     * @ORM\Column(type="text")
     */
    private $Link;

    public function getId()
    {
        return $this->id;
    }

    public function getIdFigure(): ?Trick
    {
        return $this->IdFigure;
    }

    public function setIdFigure(?Trick $IdFigure): self
    {
        $this->IdFigure = $IdFigure;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }
}

src/Form/TrickType.php
<?php
namespace App\Form;

use App\Entity\Trick;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array('label' => 'Nom'))
            ->add('description', TextareaType::class, array('label' => 'Description'))
            ->add('groupid')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Trick::class,
        ));
    }
}

templates/trick/add.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une figures{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {{ include('trick/base.html.twig') }}

            <div class="col-12">
                <div class="block p-4">
                    {{ include('form/trick.html.twig', {'button_label': 'Ajouter la figure'}) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/trick/addmedia.html.twig
{% extends "base.html.twig" %}

{% block title %}Snowtrick | Figures{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {% include('trick/base.html.twig') %}

            <div class="col-12">
                <div class="block p-4">
                {%  include('form/media.html.twig') %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/trick/base.html.twig
<div class="col-lg-12 mb-0 mt-lg-4">
    <div class="card">
        <div class="FigureImg">
            <div class="FigureUpdateBox">
                {% if is_granted('ROLE_USER') %}
                    {% if editmode == false %}
                        <a href="{{ path('app_trick_edit', {'slug' : trick.name}) }}"><i class="fa fa-pencil"></i></a>
                        <a data-toggle="modal" data-target="#myModal" class="TrickDelBtn ModalLinkConfirm" data-title="Confirmation de supression" data-content="Etes vous sur de vouloir supprimer cette figure ainsi que tout ses médias associés." href="{{ path('app_trick_trash', {'slug' : trick.name}) }}"><i class="fa fa-trash"></i></a>
                    {% else %}
                    {% endif %}
                {% endif %}</div>
            <div class="FigureName">{{ trick.name }}</div>
            <img class="card-img-top" src="{{ trick.CoverMedia ? "/uploads/medias/#{trick.CoverMedia.link}" : '/images/trickdefaultcover.jpg' }}" alt="Card image cap">
        </div>

    </div>
</div>
<div class="col-12">
    <div class="row FiguresMedia m-0 {% if trick.trickMedia|length > 0 %}pt-4{% else %}pt-0{% endif %}  d-none d-lg-flex">
        {% for medias in trick.trickMedia %}
        <div class="col-lg-2 FigureBox mb-3">
            <div class="card">
                {% if medias.VideoEmbed == null %}
                <img class="card-img-media" src="/uploads/medias/{{ medias.tempLink ? medias.tempLink : medias.link }}" alt="{{ medias.title }}">
                {% else %}
                    {{ medias.VideoEmbed|raw }}
                {% endif %}
            </div>
            <div>
                {% if is_granted('ROLE_USER') %}
                    {% if editmode == true %}
                        <a href="{{ path('app_mediaedit', {'index' : medias.id}) }}" data-id="{{ medias.id }}"><i class="fa fa-pencil"></i></a>
                        <a href="#"  data-toggle="modal" data-target="#mediaModal" data-id="{{ medias.id }}" class="TrickTrashBtn2 ModalLinkConfirm"><i class="fa fa-trash"></i></a>
                        {% if medias.VideoEmbed == null %}
                            <a href="#" data-id="{{ medias.id }}" data-trick="{{ trick.id }}" data-trickname="{{ trick.name }}" class="TrickSetMasterPic"><i class="fa fa-arrow-circle-up"></i></a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>

        </div>
        {% endfor %}
        {% if editmode == true %}<div class="text-center col-lg-12 pt-4 pb-4" style="background:#575757;"><a class="btn btn-success text-white" href="{{ path('app_trick_addmedia', {'slug' : trick.id}) }}">Ajouter un media</a></div>{% endif %}
    </div>
    <div class="row FiguresMedia m-0 pt-4 d-block d-lg-none text-center"><a href="#" class="btn btn-success mb-3 ShowMedia">Voir les médias</a></div>
</div>

templates/trick/detail.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ trick.name}}{% endblock %}

{% block body %}
    <div class="container">
        {% if trick is null %}
        <div>Cette figure n'existe pas</div>
        {% else %}
        <div class="row">
                {% include('trick/base.html.twig') %}
            <div class="col-12">
                <div class="block pl-4 pr-4 text-center row m-0">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-10">{{ trick.description }}</div>
                </div>
            </div>
            <div class="col-12 TrickBottom">
                <div class="block pl-4 pr-4 align-items-center justify-content-center row m-0 pt-2 pb-2">
                   <div class="col-lg-8 row align-middle align-items-center justify-content-center">
                        <div class="p-2 mr-2 mb-2" style="background:#575757;color:#fff;border-radius:5px;">Groupe : {{ trick.groupid.name }}</div>
                        <div class="p-2 mr-2 mb-2" style="background:#575757;color:#fff;border-radius:5px;">Création : {{ trick.publishedAt|date("m/d/Y H:i") }}</div>
                        {% if trick.updatedDate > trick.publishedAt %}<div class="p-2 mr-2 mb-2" style="background:#575757;color:#fff;border-radius:5px;">Modification : {{ trick.updatedDate|date("d/m/Y H:i") }}</div>{% endif %}
                    </div>
                </div>
            </div>
            {% if is_granted('ROLE_USER') %}
            <div class="col-12">
                <div class="block pl-4 pr-4 align-items-center justify-content-center row m-0 pt-2 pb-3 bb bt" style="background: #575757;color: #fff;">
                    <div class="text-left w-100">Ajouter un commentaire</div>
                    {% include 'form/comment.html.twig' %}
                </div>
            </div>
            {% endif %}
            <div class="col-12">
                <div class="block align-items-center justify-content-center row m-0 pt-2 pb-2 CommentBox">
                {% for comment in comments %}
                    <div class="col-lg-12 CommentData row p-0 pt-3 pb-3">
                        <div class="" style="width:120px;padding:0 20px;"><img src="{{ comment.authorid.avatar ? "/uploads/avatars/#{comment.authorid.avatar}" : '/images/noavatar.png' }}" width="100" alt="avatar"></div>
                        <div class="pl-3" style="flex:1;">
                            <b>Ecrit par <span class="Author">{{ comment.authorid.username }}</span>, le <span class="Date">{{ comment.updatedate|date('d/m/Y') }}</span></b><br />
                            <span class="Content">{{  comment.content }}</span>
                        </div>
                    </div>
                {% else %}
                    <div class="p-4 text-center">Aucun commentaire sur la figure</div>
                {% endfor %}
                </div>

                {% if comments|length %}
                <div class="block p-2 text-center">
                    <a href="#" class="LoadMoreComment" data-id="{{ trick.id }}" data-index="{{ commpentbaseindex }}" data-baseindex="{{ commpentbaseindex }}">Charger plus</a>
                </div>
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/trick/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Edition d'une figure{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {% include('trick/base.html.twig') %}

            <div class="col-12">
                <div class="block p-4">
                {%  include('form/trick.html.twig') %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/trick/list.html.twig
{% extends "base.html.twig" %}

{% block title %}Figures{% endblock %}

{% block body %}
    <div class="container">
        <header class="TitleWhite text-center">
            Les figures
        </header>
        <div class="row FiguresList" id="figures">
            {% for trick in tricks %}
                <div class="col-lg-4 p-4">
                    <div class="card">
                        <img class="card-img-top card-img-top-list" src="{{ trick.coverMedia ? "/uploads/medias/#{trick.coverMedia.link}" : '/images/figures/default.jpg' }}" alt="Card image cap">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-8">
                                    <h5 class="card-title m-0"><a href="{{ path('app_trick', {'slug' : trick.name}) }}">{{ trick.name }}</a></h5>
                                    <small>{{ trick.groupid.name }}</small>
                                </div>
                                <div class="col-4 text-right TrickIcon">
                                    {% if is_granted('ROLE_USER') %}
                                    <a href="{{ path('app_trick_edit', {'slug' : trick.name}) }}"><i class="fa fa-pencil"></i></a>
                                    <a data-toggle="modal" data-target="#myModal" class="TrickDelBtn ModalLinkConfirm" data-title="Confirmation de supression" data-content="Etes vous sur de vouloir supprimer cette figure ainsi que tout ses médias associés." href="{{ path('app_trick_trash', {'slug' : trick.name}) }}"><i class="fa fa-trash"></i></a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if is_granted('ROLE_USER') %}
        <div class="block text-center"><a class="m-4 btn btn-primary" href="{{ path('app_trick_new') }}">Ajouter une figure</a></div>
        {% endif %}
    </div>
{% endblock %}